function(__check_attribute_compatibility)
    check_feature_supported("weak" "__attribute__((weak)) void test_weak(void) {} int main() { return 0; }" HAS_WEAK_ATTR)
    if (NOT HAS_WEAK_ATTR)
        message(FATAL_ERROR "[cc][attribute]: Compiler does not support weak attribute which is required for unit tests.")
        return()
    endif ()

    check_feature_supported("noinline" "__attribute__((noinline)) void test_target(void) {} int main() { return 0; }" HAS_NOINLINE_ATTR)
    if (NOT HAS_NOINLINE_ATTR)
        message(FATAL_ERROR "[cc][attribute]: Compiler does not support target attribute which is required for unit tests.")
        return()
    endif ()
endfunction()

function(__check_header_compatibility)
    check_header_supported("sys/event.h" HAS_EVENT_H)
    check_header_supported("sys/epoll.h" HAS_EPOLL_H)
    if (NOT HAS_EVENT_H AND NOT HAS_EPOLL_H)
        message(FATAL_ERROR "[cc][header]: Header file 'sys/event.h' or 'sys/epoll.h' must be available in the standard library.")
        return()
    endif ()
endfunction()

function(__check_platform_compatibility)
    if (NOT UNIX AND NOT APPLE)
        message(FATAL_ERROR "[cc][platform]: Operation system must be a unix or apple platform.")
        return()
    endif ()
endfunction()

function(check_feature_supported FEATURE CODE OUTPUT)
    string(TOUPPER "${FEATURE}" FEATURE_NAME)
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" VAR "HAS_CC_FEATURE_${FEATURE_NAME}")
    set(CMAKE_REQUIRED_FLAGS "-Werror")
    check_c_source_compiles("${CODE}" ${VAR})
    set(${OUTPUT} ${${VAR}} PARENT_SCOPE)
    unset(CMAKE_REQUIRED_FLAGS)
endfunction()

function(check_header_supported HEADER OUTPUT)
    string(TOUPPER "${HEADER}" HEADER_NAME)
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" VAR "HAS_CC_HEADER_${HEADER_NAME}")
    check_include_file("${HEADER}" ${VAR})
    set(${OUTPUT} ${${VAR}} PARENT_SCOPE)
endfunction()

function(check_flag_supported FLAG OUTPUT)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
    string(TOUPPER "${FLAG}" FLAG_NAME)
    string(REGEX REPLACE "[^a-zA-Z0-9]" "_" VAR "HAS_CC_FLAG_${FLAG_NAME}")
    check_c_compiler_flag("${FLAG}" ${VAR})
    set(${OUTPUT} ${${VAR}} PARENT_SCOPE)
    unset(CMAKE_TRY_COMPILE_TARGET_TYPE)
endfunction()

function(target_supported_headers TARGET SCOPE FLAGS)
    foreach (FLAG IN LISTS FLAGS)
        check_flag_supported("${FLAG}" IS_SUPPORTED)
        if (IS_SUPPORTED)
            target_compile_options(${TARGET} ${SCOPE} "${FLAG}")
        else ()
            message(STATUS "[cc][flag]: Flag is not supported on this platform: '${FLAG}'.")
        endif ()
    endforeach ()
endfunction()

function(target_supported_sources HEADER TARGET SCOPE C_FILE)
    check_header_supported(${HEADER} IS_SUPPORTED)
    if (IS_SUPPORTED)
        target_sources(${TARGET} ${SCOPE} "${C_FILE}")
        message(STATUS "[cc][code]: Source code '${C_FILE}' is added to target ${TARGET}.")
    else ()
        message(STATUS "[cc][code]: Source code '${C_FILE}' is skipped due to missing header ${HEADER}.")
    endif ()
endfunction()

function(test_system_compatibility)
    set(CMAKE_REQUIRED_FLAGS "-Werror")
    __check_platform_compatibility()
    __check_header_compatibility()
    __check_attribute_compatibility()
    unset(CMAKE_REQUIRED_FLAGS)
endfunction()
