name: JPipe - CMake Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [ gcc, clang ]
    
    steps:
      - uses: actions/checkout@v6

      - name: Install
        run: sudo apt-get update && sudo apt-get install -y clang gcc llvm

      - name: Address Sanitizer Flow
        env:
          CC: ${{matrix.compiler}}
          ASAN_OPTIONS: "detect_leaks=1:exitcode=1"
        run: make test-with-asan

      - name: Thread Sanitizer Flow
        env:
          CC: ${{matrix.compiler}}
          TSAN_OPTIONS: "halt_on_error=1"
        run: setarch $(uname -m) -R make test-with-tsan
  
  analyze:
    name: Code Quality
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    
    steps:
      - uses: actions/checkout@v6

      - name: Install
        run: sudo apt-get update && sudo apt-get install -y clang gcc llvm lcov gcovr

      - name: CodeQL Initialization
        uses: github/codeql-action/init@v4
        with:
          languages: c-cpp
          config-file: .github/codeql/codeql-config.yml
          build-mode: manual

      - name: Coverage Flow
        env:
          CC: gcc
        run: make coverage

      - name: Code Formatting Flow
        run: make format

      - name: CodeQL Reporting
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:c-cpp"

      - name: Coverage Reporting
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: lcov
          file: build_current/coverage_filtered.info
